GET http://localhost:8000/users/current-user/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNlNyc1VTYjZnOWp3eUxobzVicEJOWEVnUUUiLCJvaWF0IjoxNzgyMjk1Mjg4LCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3ODIyOTUzNDgsImZ2YSI6WzM5LC0xXSwiaWF0IjoxNzgyMjk1Mjg4LCJpc3MiOiJodHRwczovL2NlbnRyYWwtd2FzcC05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3ODIyOTUyNzgsInNpZCI6InNlc3NfM0ZacU5zdlFEWEJEeDdoaTlNWTJybXNLY3dkIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zRXlVeE43azhMTFpObmpzRUFvdDVaelpzV0UiLCJ2IjoyfQ.IotR_66TQUvQVhxqFQ4sgzkTftcUeeusqG_IjHNKac9Tv0FcqOnj73xi0B-1PdadzXBz1s81_bZxlWxv2vrDATfFm6r5PJGVNVI7QYD0WgOZy4NSvoThOv3kdVX3_MY_ZVeRaEq0-YrxuNrbC2l-NNpjn8M3Lxvqm7Hsx5gmYBaEWFx0Yqzp9r0cYQeqUrAwGdpJRZvFSdxCWAKFgoB1XC3JydFsIK1Lro-SzwpFbfhI0wNBU0cMAGkH2DCjP1jKiqocUaZ7XrArnKme1cvKbFrjqRlljVZaL87H_FBf4LjTIl7QK_gzZAV5P0cd-DqJeT1wgWHJgkt4S97jL109Xg

