services:
  worker:
    build: ./server
    container_name: celery-worker
    entrypoint: ./scripts/worker.entrypoint.sh
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.local
    depends_on:
      - redis
      - db
      - django

  beat:
    build: ./server
    container_name: celery-beat
    entrypoint: ./scripts/beat.entrypoint.sh
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.local
    depends_on:
      - redis
      - db
      - django

  flower:
    build: ./server
    container_name: celery-flower
    command: ./scripts/flower.entrypoint.sh
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.local
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
      - django

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./server/.env.local

  django:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.local
    depends_on:
      - db
      - redis
      - elasticsearch

volumes:
  postgres_data:
  redis_data:
  esdata: