services:
  web:
    build:
      context: ./packages/web
      dockerfile: ./Dockerfile
      
    ports:
      - 5173:5173
    env_file:
      - ./packages/web/.env
    develop:
      watch:
        - action: sync
          path: ./packages/web/src
          target: ./app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/web/bun.lock
        - action: rebuild
          path: ./packages/web/package.json
        - action: rebuild
          path: ./packages/web/vite.config.ts
          target: ./app/vite.config.ts

  api:
    restart: unless-stopped
    build:
      context: ./packages/api
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 8000:8000
    env_file:
      - ./packages/api/.env
    develop:
      watch:
        - action: sync
          path: ./packages/api
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - .git/
            - .venv/
        - action: rebuild
          path: ./packages/api/pyproject.toml
        - action: rebuild
          path: ./packages/api/uv.lock

  inngest:
    image: inngest/inngest:latest
    command: 'inngest dev -u http://api:8000/api/inngest --no-discovery'
    ports:
      - 8288:8288
    depends_on:
      api:
        condition: service_started


