# Generated by Django 6.0.7 on 2026-07-26 23:11

from django.db import migrations


def generate_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    User = apps.get_model("accounts", "User")
    groups = ["Student", "Educator", "Admin"]

    for group in groups:
        Group.objects.get_or_create(name=group)

    user_ct = ContentType.objects.get_for_model(User)
    perm, _ = Permission.objects.get_or_create(
        codename="can_go_haridwar", name="Can go to Haridwar", content_type=user_ct
    )


def rollback_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Student", "Instructor", "Admin"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_groups, reverse_code=rollback_groups)]
