# Generated by Django 6.0.6 on 2026-07-22 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIGenerationLog",
        ),
    ]
