# Generated by Django 6.0.6 on 2026-07-22 09:59

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_aigenerationlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="onboarding_completed",
            new_name="is_removed",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_active_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="learning_goal",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="preferred_difficulty",
        ),
        migrations.RemoveField(
            model_name="usertrophy",
            name="earned_at",
        ),
        migrations.AddField(
            model_name="profile",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertrophy",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="usertrophy",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertrophy",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="usertrophy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
    ]
