# Generated by Django 6.0.7 on 2026-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_setup_rbac_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
