# Generated by Django 6.1 on 2026-09-02 15:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_options_remove_user_role_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="",
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="avatars/%y/%m/%d",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EDUCATOR", "Educator"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("PREMIUM", "Premium"),
                    ("PRO", "Pro"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                max_length=20,
                verbose_name="tier",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="clerk_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["clerk_id"], name="accounts_us_clerk_i_3e5530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
