# Generated by Django 6.1 on 2026-09-02 16:51

import accounts.models
import cloudinary_storage.storage
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_remove_profile_user_user_picture_user_role_user_tier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clerk_id",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2026, 9, 2, 16, 51, 2, 568820, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                default=accounts.models._gravatar_url,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="avatars/%y/%m/%d",
            ),
        ),
    ]
