# Generated by Django 6.1 on 2026-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_clerk_id_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clerk_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
