# Generated by Django 6.0.5 on 2026-06-20 09:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("file", models.URLField(verbose_name="file")),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="object_id",
        ),
        migrations.AddField(
            model_name="tag",
            name="content_type",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="object_id",
            field=models.PositiveBigIntegerField(
                default=datetime.datetime(
                    2026, 6, 20, 9, 26, 27, 7456, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["content_type", "object_id"], name="shop_tag_content_0c1622_idx"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                related_query_name="resource",
                to="shop.lesson",
                verbose_name="lesson",
            ),
        ),
    ]
