# Generated by Django 6.0.3 on 2026-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Designates whether this item is active or has been removed.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Designates whether this item is active or has been removed.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Designates whether this item is active or has been removed.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Designates whether this item is active or has been removed.', verbose_name='Active'),
        ),
    ]
