# Generated by Django 6.0.5 on 2026-06-23 16:43

import cloudinary_storage.storage
import common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=common.fields.HybridImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="avatars/%Y/%m/%d",
                verbose_name="picture",
            ),
        ),
    ]
