# Generated by Django 6.1 on 2026-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_category_date_created_category_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "course", "verbose_name_plural": "courses"},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="courses_cat_slug_33564e_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["category"], name="courses_cou_categor_108713_idx"
            ),
        ),
    ]
