GET http://localhost:8000/users/current-user/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNlNyc1VTYjZnOWp3eUxobzVicEJOWEVnUUUiLCJvaWF0IjoxNzg0MDU5NDAzLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3ODQwNTk0NjMsImZ2YSI6WzE4LC0xXSwiaWF0IjoxNzg0MDU5NDAzLCJpc3MiOiJodHRwczovL2NlbnRyYWwtd2FzcC05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3ODQwNTkzOTMsInNpZCI6InNlc3NfM0dWWWdaSWpyS1l3Q2ZPamxtenlPTjZnZEpiIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zR1ZTa1hMQ3UzYzc5QjYzU21jc0EyazFpT2YiLCJ2IjoyfQ.wPLDjzPskDiHkdH2KkDKee9ffOOa8ZIAv-f0S0J3Z_uV7TLWWNvInzGK5ABZI6yZLjMsaZaB3P2iojtNVR3-cCS85NqzKV6AQcyzUuEqy55rDGCa3-sgFRuOM4nWb3BilcEaz-0KRFZwLxOTnpC0NonABUZ2HgqrI0yvz5EPoYYl_gi1RGb61AozelFmobSHbp2hP4EVAhlYa6RawBRw8XCzdketRgUBc3WAHZcvUCQSVD88tByQCMg3DL6c0qWOsxPtxrZvj_UjVxiaoWMFeYOiRns1vEf-Dsd_sJqdiM-Y-vKFyLuZ0TiUyoej0LHK0ewwRmhWw-jD7Zm_63yrRA