GET http://localhost:8000/categories/ HTTP/1.1

###
GET http://localhost:8000/users/current-user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNlNyc1VTYjZnOWp3eUxobzVicEJOWEVnUUUiLCJvaWF0IjoxNzg4MzI2MDc5LCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEiLCJleHAiOjE3ODgzMjYxMzksImZ2YSI6WzcxLC0xXSwiaWF0IjoxNzg4MzI2MDc5LCJpc3MiOiJodHRwczovL2NlbnRyYWwtd2FzcC05Ny5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3ODgzMjYwNjksInNpZCI6InNlc3NfM0lrd0ZMb2JweUFRd2tSNWxOVmIzOTdVT0RWIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zSWtuckhxUzlOcFFMbjJEUEVlRFJUaG9HUTgiLCJ2IjoyfQ.gJfjskYc28L96VLs5_6WUBB9PP1mF1P2Msb2yn2nm3mOjpku7DZYpI0-z-542BrBdMBvVAQlKjFJ-TNMmY9ktHMWkfBmBcgsltRRcC_kA8lwdFbRPcSDfi-dgA9XF2pmFGNEBGQeqELdNtC8R_9oH8wkXkRkq4Lac9acadwzBFgurJGI9SvwD_Z8PqD1vJcLim0d2azPWPx4gteh3A_T6h2iOB20geHjgeSxwaeeJ7jQwqVyEhbHgRouekoS1ywtTRX9tHqRYgQYIjUXPyFCYSaY-5AFTs3W4wufWP50Q6a9tyQgmcM2Q5pITkiy6L2_1OsuSdz9dOTNpgNEjVZJzQ