[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
FAIL_INVALID_TEMPLATE_VARS = True
testpaths = apps tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
django_debug_mode = keep
addopts =
    --reuse-db
    --nomigrations
    --cov=apps
    --cov-report=html
    --cov-report=term-missing
    --strict-markers
markers =
    slow: marks tests as slow
    integration: marks tests as integration tests