# Generated by Django 5.2.7 on 2025-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='A short label, generally used in URLs.', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='A short label, generally used in URLs.', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(help_text='A short label, generally used in URLs.', max_length=255),
        ),
    ]
