# Generated by Django 5.2.8 on 2025-11-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'name')},
        ),
    ]
