# Generated by Django 5.2.7 on 2025-10-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_category_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'name')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
