# Generated by Django 6.0.6 on 2026-07-08 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=125, unique=True, verbose_name="title"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=125, unique=True, verbose_name="title"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="resources/%Y/%m/%d")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses",
                        to="content.category",
                        verbose_name="list of categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=125, unique=True, verbose_name="title"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="resources/%Y/%m/%d")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("title", models.CharField(max_length=125, verbose_name="title")),
                ("video_url", models.URLField(blank=True, verbose_name="video")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        related_query_name="lesson",
                        to="content.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "ordering": ["-date_created"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "course"), name="unique_title_course"
                    )
                ],
            },
        ),
    ]
