# Generated by Django 6.0.6 on 2026-07-15 16:01

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=core.fields.DynamicImageURLField(blank=True, null=True, upload_to='resources/%Y/%m/%d', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=core.fields.DynamicImageURLField(blank=True, null=True, upload_to='resources/%Y/%m/%d', verbose_name='thumbnail'),
        ),
    ]
