# Generated by Django 6.0.5 on 2026-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Uncheck this box to active the record.",
                verbose_name="active",
            ),
        ),
    ]
