# Generated by Django 6.0.5 on 2026-06-14 05:43

import uuid

import cloudinary_storage.storage
import core.models.managers
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "clerk_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="avatars/%Y/%m/%d",
                        verbose_name="picture",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("USER", "User"),
                            ("TEACHER", "Teacher"),
                        ],
                        default="USER",
                        max_length=8,
                        verbose_name="role",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["date_joined"],
            },
            managers=[
                ("objects", core.models.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["date_created"],
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Question"),
                            ("ESSAY", "Essay"),
                        ],
                        default="MCQ",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_premium_member",
                    models.BooleanField(default=False, verbose_name="premium member"),
                ),
                (
                    "has_support_contract",
                    models.BooleanField(default=False, verbose_name="support contract"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="courses/%Y/%m/%d")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses",
                        to="core.category",
                        verbose_name="list of categories",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        related_query_name="course",
                        to="core.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("CO", "Completed"),
                            ("CA", "Cancelled"),
                        ],
                        default="PE",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("role", "USER")),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "enrollment",
                "verbose_name_plural": "enrollments",
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier used for the URL of this record.",
                        unique=True,
                        verbose_name="URL-friendly",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("video_url", models.URLField(blank=True, verbose_name="video")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        related_query_name="lesson",
                        to="core.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("is_liked", models.BooleanField(default=False, verbose_name="liked")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("role", "USER")),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "like",
                "verbose_name_plural": "likes",
                "ordering": ["date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="total price",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="transaction id"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("momo", "MoMo"),
                            ("vnpay", "VNPAY"),
                            ("stripe", "STRIPE"),
                        ],
                        default="stripe",
                        max_length=10,
                        verbose_name="method",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.enrollment",
                        verbose_name="enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("content", models.CharField(max_length=125)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("description", models.TextField(blank=True)),
                ("score", models.FloatField(default=50.0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        related_query_name="quiz",
                        to="core.lesson",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_created",
                        related_query_name="quizzes",
                        to="core.teacher",
                        verbose_name="creator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.quiz",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("file", models.URLField(verbose_name="file")),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        related_query_name="resource",
                        to="core.lesson",
                        verbose_name="lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("is_graded", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("role", "USER")),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        related_query_name="submission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.choice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="name"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("content", models.TextField(verbose_name="content")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("role", "USER")),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["date_created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_commen_content_37d5bd_idx",
                    )
                ],
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(auto_now=True, verbose_name="date changed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to deactivate the record instead of deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "certificate_code",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="certificate code",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="pdf url"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("role", "USER")),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "course"),
                        name="core_certificate_unique_student_course",
                    )
                ],
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course"),
                name="core_enrollment_unique_student_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("name", "course"), name="unique_name_course"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_like_content_c5c987_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("creator", "content_type", "object_id"),
                name="unique_liked_creator",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("student", "quiz"), name="unique_student_quiz_submission"
            ),
        ),
    ]
