[pytest]
DJANGO_SETTINGS_MODULE = core.settings.local
python_files = tests.py test_*.py *_tests.py
addopts = -p no:warnings --no-migrations --reuse-db
    --cov=. 
    --cov-report=xml:coverage/coverage.xml 
    --cov-report=html:coverage/htmlcov 
    --cov-report=json:coverage/coverage.json
    --cov-report=term-missing
    -v