# Generated by Django 6.0.6 on 2026-07-14 16:22

import cloudinary_storage.storage
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('clerk_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('TEACHER', 'Teacher')], default='USER', max_length=8, verbose_name='role')),
                ('subscription_id', models.CharField(max_length=125, verbose_name='subscription ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this box to deactivate the record instead of deleting it.', verbose_name='active')),
                ('level_num', models.PositiveIntegerField(help_text='Cấp độ (Ví dụ: 1, 2, 3...)', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('required_xp', models.PositiveIntegerField(default=0, help_text='Số điểm XP tối thiểu cần đạt để chạm mốc level này')),
                ('coin_reward', models.PositiveIntegerField(default=0, help_text='Số xu thưởng tặng cho user khi đạt cấp độ này')),
                ('title', models.CharField(blank=True, help_text='Tên danh hiệu của cấp độ này', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('slug', models.SlugField(help_text='A unique identifier used for the URL of this record.', unique=True, verbose_name='URL-friendly')),
                ('title', models.CharField(max_length=125, unique=True, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this box to deactivate the record instead of deleting it.', verbose_name='active')),
                ('badge', models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='badges/%Y/%m/%d', verbose_name='badge')),
                ('description', models.TextField(blank=True, help_text='Mô tả điều kiện đạt huy hiệu')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_premium_member', models.BooleanField(default=False, verbose_name='premium member')),
                ('has_support_contract', models.BooleanField(default=False, verbose_name='support contract')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='TrophyCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this box to deactivate the record instead of deleting it.', verbose_name='active')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trophy')),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this box to deactivate the record instead of deleting it.', verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('xp', models.PositiveIntegerField(default=0, help_text='Tổng điểm kinh nghiệm tích lũy')),
                ('coins', models.PositiveIntegerField(default=0, help_text='Số xu dùng để đổi quà/tính năng')),
                ('daily_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_checkin', models.DateTimeField(blank=True, null=True, verbose_name='last checkin')),
                ('credits', models.PositiveIntegerField(default=5)),
                ('current_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users_at_level', to='accounts.levels')),
                ('trophies', models.ManyToManyField(blank=True, related_name='achieved_by_stats', through='accounts.TrophyCabinet', to='accounts.trophy')),
            ],
            options={
                'verbose_name': 'user statistic',
                'verbose_name_plural': 'user statistics',
            },
        ),
        migrations.AddField(
            model_name='trophycabinet',
            name='user_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_items', to='accounts.userstats'),
        ),
        migrations.AddConstraint(
            model_name='trophycabinet',
            constraint=models.UniqueConstraint(fields=('user_stats', 'trophy'), name='unique_user_stats_trophy'),
        ),
    ]
