# Generated by Django 6.0.6 on 2026-07-15 16:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=core.fields.DynamicImageURLField(blank=True, null=True, upload_to='avatars/%Y/%m/%d', verbose_name='picture'),
        ),
    ]
